apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: demo-voting-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    # nodeport is optinal if we will not pass then dummy value will genrate
    nodePort: 30009
  selector:
    name: result-app-pod
    app: demo-voting-app
