apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: demo-voting-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
        # nodeport is optinal if we will not pass then dummy value will genrate
    nodePort: 30008
  selector:
    name: voting-app-pod
    app: demo-voting-app
